@echo off
REM Create a new conda environment named 'pygame_demos'
REM This script sets up a conda environment with Python 3.10 and Pygame installed.

REM Create the conda environment
conda create -n pygame_demos --channel conda-forge python=3.10 pygame

REM Activate the new environment
conda activate pygame_demos

REM Generated by Nicole LeGuern
