@echo off
REM Create a new conda environment named 'pygame_demos'
REM This script sets up a conda environment with Python 3.8 and Pygame installed.

REM Create the conda environment
conda create -n pygame_demos --channel conda-forge python=3.8 pygame

REM Generated by Nicole LeGuern
