import os

def create_folders():
    folders = [
        "snake_game",
        "snake_game/assets",
        "snake_game/assets/sounds",
        "snake_game/assets/music",
        "snake_game/logs",
        "snake_game/database"
    ]

    for folder in folders:
        try:
            os.makedirs(folder, exist_ok=True)
            print(f"Created folder: {folder}")
        except Exception as e:
            print(f"Error creating folder {folder}: {e}")

if __name__ == "__main__":
    create_folders()
    print("All required folders have been created.")
# Generated by Nicole LeGuern