import pygame
import random
from utils import log_error

class Game:
    def __init__(self, screen):
        self.screen = screen
        self.snake = [(100, 100), (90, 100), (80, 100)]
        self.direction = pygame.K_RIGHT
        self.food = self.generate_food()
        self.score = 0
        self.level = 1
        self.speed = 10

    def handle_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                exit()
            elif event.type == pygame.KEYDOWN:
                if event.key in [pygame.K_UP, pygame.K_DOWN, pygame.K_LEFT, pygame.K_RIGHT]:
                    self.direction = event.key

    def update(self):
        head = self.snake[0]
        if self.direction == pygame.K_UP:
            new_head = (head[0], head[1] - 10)
        elif self.direction == pygame.K_DOWN:
            new_head = (head[0], head[1] + 10)
        elif self.direction == pygame.K_LEFT:
            new_head = (head[0] - 10, head[1])
        elif self.direction == pygame.K_RIGHT:
            new_head = (head[0] + 10, head[1])
        
        self.snake = [new_head] + self.snake[:-1]
        
        if self.snake[0] == self.food:
            self.snake.append(self.snake[-1])
            self.food = self.generate_food()
            self.score += 10
            if self.score % 50 == 0:
                self.level += 1
                self.speed += 2

        if self.snake[0] in self.snake[1:] or not (0 <= self.snake[0][0] < 800 and 0 <= self.snake[0][1] < 600):
            self.game_over()

    def draw(self):
        self.screen.fill((0, 0, 0))
        for segment in self.snake:
            pygame.draw.rect(self.screen, (0, 255, 0), (*segment, 10, 10))
        pygame.draw.rect(self.screen, (255, 0, 0), (*self.food, 10, 10))
        self.draw_text(f"Score: {self.score}", 10, 10)
        self.draw_text(f"Level: {self.level}", 10, 30)

    def generate_food(self):
        return (random.randint(0, 79) * 10, random.randint(0, 59) * 10)

    def draw_text(self, text, x, y):
        font = pygame.font.Font(None, 36)
        text_surface = font.render(text, True, (255, 255, 255))
        self.screen.blit(text_surface, (x, y))

    def game_over(self):
        self.draw_text("Game Over", 400, 300)
        pygame.display.flip()
        pygame.time.wait(2000)
        pygame.quit()
        exit()
# Generated by Nicole LeGuern