import pygame
from game import Game
from leaderboard import Leaderboard
from user import User
from sound import Sound
from utils import log_error

def main():
    pygame.init()
    screen = pygame.display.set_mode((800, 600))
    pygame.display.set_caption("Snake Game")
    clock = pygame.time.Clock()
    game = Game(screen)
    leaderboard = Leaderboard()
    sound = Sound()
    
    try:
        while True:
            game.handle_events()
            game.update()
            game.draw()
            pygame.display.flip()
            clock.tick(game.speed)
    except Exception as e:
        log_error("main", str(e))
    finally:
        pygame.quit()

if __name__ == "__main__":
    main()
# Generated by Nicole LeGuern