import pygame
from utils import log_error

class Sound:
    def __init__(self):
        try:
            pygame.mixer.init()
            self.eat_sound = pygame.mixer.Sound("assets/sounds/eat.wav")
            self.game_over_sound = pygame.mixer.Sound("assets/sounds/game_over.wav")
            self.background_music = "assets/music/background.mp3"
            pygame.mixer.music.load(self.background_music)
            pygame.mixer.music.play(-1)
        except Exception as e:
            log_error("Sound.__init__", str(e))

    def play_eat_sound(self):
        try:
            self.eat_sound.play()
        except Exception as e:
            log_error("play_eat_sound", str(e))

    def play_game_over_sound(self):
        try:
            self.game_over_sound.play()
        except Exception as e:
            log_error("play_game_over_sound", str(e))

    def toggle_music(self):
        try:
            if pygame.mixer.music.get_busy():
                pygame.mixer.music.stop()
            else:
                pygame.mixer.music.play(-1)
        except Exception as e:
            log_error("toggle_music", str(e))
# Generated by Nicole LeGuern