import pygame
from game import Game
from leaderboard import Leaderboard
from admin import AdminPanel

def main():
    pygame.init()
    screen = pygame.display.set_mode((800, 600))
    pygame.display.set_caption("Snake Game Test")

    game = Game(screen)
    leaderboard = Leaderboard()
    admin_panel = AdminPanel()

    running = True
    while running:
        screen.fill((0, 0, 0))
        font = pygame.font.Font(None, 36)
        text = font.render("Main Menu", True, (255, 255, 255))
        screen.blit(text, (350, 100))

        start_game_text = font.render("1. Start Game", True, (255, 255, 255))
        screen.blit(start_game_text, (350, 200))

        view_leaderboard_text = font.render("2. View Leaderboard", True, (255, 255, 255))
        screen.blit(view_leaderboard_text, (350, 300))

        manage_users_text = font.render("3. Manage Users", True, (255, 255, 255))
        screen.blit(manage_users_text, (350, 400))

        pygame.display.flip()

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_1:
                    game.run()
                elif event.key == pygame.K_2:
                    view_leaderboard(screen, leaderboard)
                elif event.key == pygame.K_3:
                    admin_panel.run()

    pygame.quit()

def view_leaderboard(screen, leaderboard):
    screen.fill((0, 0, 0))
    font = pygame.font.Font(None, 36)
    text = font.render("Leaderboard", True, (255, 255, 255))
    screen.blit(text, (350, 100))

    top_scores = leaderboard.get_top_scores()
    y_offset = 200
    for name, score in top_scores:
        score_text = font.render(f"{name}: {score}", True, (255, 255, 255))
        screen.blit(score_text, (350, y_offset))
        y_offset += 50

    pygame.display.flip()
    pygame.time.wait(5000)

if __name__ == "__main__":
    main()

# Generated by Nicole LeGuern