import logging
import os
from datetime import datetime

# Ensure the logs directory exists
os.makedirs("logs", exist_ok=True)

logging.basicConfig(filename="logs/game.log", level=logging.ERROR)

def log_error(function_name, error_message):
    """
    Logs an error message with a timestamp and function name.

    Parameters
    ----------
    function_name : str
        The name of the function where the error occurred.
    error_message : str
        The error message to log.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    logging.error(f"{timestamp} - {function_name}: {error_message}")

# Generated by Nicole LeGuern6