import pytest
from leaderboard import Leaderboard

@pytest.fixture
def leaderboard():
    lb = Leaderboard()
    lb.clear_table()  # Clear the leaderboard table before running the tests
    return lb

def test_add_score(leaderboard):
    """
    Test adding a score to the leaderboard.
    """
    leaderboard.add_score("test_user", 100)
    top_scores = leaderboard.get_top_scores()
    assert ("test_user", 100) in top_scores

def test_get_top_scores(leaderboard):
    """
    Test retrieving the top scores from the leaderboard.
    """
    leaderboard.add_score("test_user1", 100)
    leaderboard.add_score("test_user2", 200)
    top_scores = leaderboard.get_top_scores()
    assert top_scores == [("test_user2", 200), ("test_user1", 100)]

# Generated by Nicole LeGuern