import pytest
from admin import AdminPanel

@pytest.fixture
def admin_panel():
    return AdminPanel()

def test_create_user_table(admin_panel):
    assert admin_panel.create_user_table() is None

def test_create_settings_table(admin_panel):
    assert admin_panel.create_settings_table() is None

def test_open_admin_panel_first_time(admin_panel):
    # Implement logic to check if the admin panel opens the first time the program runs
    pass

def test_manage_users(admin_panel):
    # Implement logic to test create, read, update, delete functions for users
    pass

def test_configure_game_length(admin_panel):
    # Implement logic to test configuring the length of game time
    pass

def test_configure_food_size(admin_panel):
    # Implement logic to test configuring the food size
    pass

def test_configure_game_window_size(admin_panel):
    # Implement logic to test configuring the game window size
    pass

# Generated by Nicole LeGuern