import pytest
import os
from create_game_folders import create_folders

def test_create_folders():
    create_folders()
    folders = [
        "snake_game",
        "snake_game/assets",
        "snake_game/assets/sounds",
        "snake_game/assets/music",
        "snake_game/logs",
        "snake_game/database"
    ]
    for folder in folders:
        assert os.path.exists(folder)

# Generated by Nicole LeGuern