import pytest
from leaderboard import Leaderboard

@pytest.fixture
def leaderboard():
    return Leaderboard()

def test_create_table(leaderboard):
    assert leaderboard.create_table() is None

def test_add_score(leaderboard):
    assert leaderboard.add_score("Player1", 100) is None

def test_get_top_scores(leaderboard):
    scores = leaderboard.get_top_scores()
    assert isinstance(scores, list)

# Generated by Nicole LeGuern