import pytest
import pygame
from game import Game

@pytest.fixture
def game():
    pygame.init()
    screen = pygame.display.set_mode((800, 600))
    return Game(screen)

def test_handle_events(game):
    assert game.handle_events() is None

def test_generate_food(game):
    food = game.generate_food()
    assert isinstance(food, tuple)
    assert len(food) == 2

def test_update(game):
    assert game.update() is None

def test_draw(game):
    assert game.draw() is None

# Generated by Nicole LeGuern