import pytest
from user import User

@pytest.fixture
def user():
    return User(name="test_user")

def test_create_user(user):
    """
    Test creating a new user.
    """
    user.add_user("test_user", "password")
    assert user.authenticate_user("test_user", "password")

def test_read_user(user):
    """
    Test reading user information.
    """
    user.add_user("test_user", "password")
    assert user.authenticate_user("test_user", "password")

def test_update_user(user):
    """
    Test updating user information.
    """
    user.add_user("test_user", "password")
    user.update_user("test_user", "new_password")
    assert user.authenticate_user("test_user", "new_password")

def test_delete_user(user):
    """
    Test deleting a user.
    """
    user.add_user("test_user", "password")
    user.delete_user("test_user")
    assert not user.authenticate_user("test_user", "password")

# Generated by Nicole LeGuern